# -------------------------------------------------------------------------------------
# Build Configuration
# See: https://gohugo.io/configuration/build/
# -------------------------------------------------------------------------------------

noJSConfigInAssets = true
