# -------------------------------------------------------------------------------------
# Imaging Configuration
# See: https://gohugo.io/configuration/imaging/
# -------------------------------------------------------------------------------------

_merge = "shallow"

[jpeg]
quality = 75

[webp]
quality = 75

[avif]
quality = 75
