# -------------------------------------------------------------------------------------
# Modules Configuration
# See: https://gohugo.io/configuration/module/
# -------------------------------------------------------------------------------------

[[imports]]
path = "github.com/hugo-fixit/fixit-bundle"

[[imports]]
path = "github.com/Artexxx/cmpt-post-preview"
version = "latest"

[[imports]]
path = "github.com/hugo-fixit/cmpt-markmap"

[hugoVersion]
extended = true
min = "0.156.0"
