# -------------------------------------------------------------------------------------
# Output Configuration
# See: https://gohugo.io/configuration/outputs/
# -------------------------------------------------------------------------------------

# options to make hugo output files, the available values are below:
# home = ["html", "rss", "atom", "jsonfeed", "archives", "search", "offline", "manifest", "link", "readme", "baidu_urls"]
# page = ["html", "markdown"]
# section = ["html", "rss", "jsonfeed"]
# taxonomy = ["html"]
# term = ["html", "rss", "jsonfeed"]

_merge = "shallow"
home = [
  "html",
  "rss",
  "jsonfeed",
  "archives",
  "offline",
  "search",
  "manifest",
  "readme",
  "link",
  "readme",
  "baidu_urls"
]
page = [
  "html",
  "markdown"
]
section = [
  "html",
  "rss",
  "jsonfeed"
]
taxonomy = [ "html" ]
term = [
  "html",
  "rss",
  "jsonfeed"
]
