# -------------------------------------------------------------------------------------
# Theme Core Configuration
# See: https://fixit.lruihao.cn/theme-documentation-basics/#site-configuration
# -------------------------------------------------------------------------------------

# FixIt theme version
version = "0.2.X"
# site description
description = "Lruihao's Note 李瑞豪的博客：探索、分享、记录自己在工作生活学习到一些东西。人知道得越多，就就会发现无知的越多。有更广袤世界可以探索，真是莫大的快乐啊！"
# site keywords
keywords = ["李瑞豪", "李瑞豪的博客", "菠菜眾長", "博採眾長", "Lruihao", "Cell", "Hugo Blog"]
# site default theme ("light", "dark", "auto")
defaultTheme = "auto"
# date format
dateFormat = "2006-01-02"
# website images for Open Graph and Twitter Cards
images = ["/images/apple-devices-preview.webp"]
# FixIt 0.2.12 | NEW enable PWA
enablePWA = true
# FixIt 0.2.14 | NEW whether to add external Icon for external links automatically
externalIcon = true
# FixIt 0.3.0 | NEW whether to reverse the order of the navigation menu
navigationReverse = true
# FixIt 0.3.0 | NEW whether to add site title to the title of every page
# remember to set up your site title in `hugo.toml` (e.g. title = "title")
withSiteTitle = true
# FixIt 0.3.0 | NEW title delimiter when the site title is be added to the title of every page
titleDelimiter = "|"
# FixIt 0.3.0 | NEW whether to add site subtitle to the title of index page
# remember to set up your site subtitle by `params.header.subtitle.name`
indexWithSubtitle = true
# FixIt 0.2.14 | NEW FixIt will, by default, inject a theme meta tag in the HTML head on the home page only.
# You can turn it off, but we would really appreciate if you don’t, as this is a good way to watch FixIt's popularity on the rise.
disableThemeInject = false

# Author Configuration
[author]
  name = "Lruihao"
  email = "1024@lruihao.cn"
  link = "https://github.com/Lruihao"
  avatar = "/images/avatar.jpg"

# FixIt 0.3.0 | NEW public Git repository information only then enableGitInfo is true
[gitInfo]
  # e.g. "https://github.com/hugo-fixit/docs"
  repo = "https://github.com/Lruihao/hugo-blog"
  branch = "docs"
  # the content directory path relative to the root of the repository
  dir = "content"
  # the issue template for reporting issue of the posts
  # available template params: {title} {URL} {sourceURL}
  issueTpl = "title=[BUG]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|URL|{URL}|%0A|Filename|{sourceURL}|"

# App icon config
[app]
  # optional site title override for the app when added to an iOS home screen or Android launcher
  title = "菠菜眾長"
  # whether to omit favicon resource links
  noFavicon = false
  # modern SVG favicon to use in place of older style .png and .ico files
  svgFavicon = ""
  # Safari mask icon color
  iconColor = "#5bbad5"
  # Windows v8-10 tile color
  tileColor = "#da532c"
  # FixIt 0.2.12 | CHANGED Android browser theme color
  [app.themeColor]
    light = "#ffffff"
    dark = "#252627"

# Search config
[search]
  enable = true
  # type of search engine ("lunr", "algolia")
  type = "algolia"
  # max index length of the chunked content
  contentLength = 4000
  # placeholder of the search bar
  placeholder = ""
  # max number of results length
  maxResultLength = 10
  # snippet length of the result
  snippetLength = 50
  # HTML tag name of the highlight part in results
  highlightTag = "em"
  # whether to use the absolute URL based on the baseURL in search index
  absoluteURL = false
  [search.algolia]
    index = "index"
    appID = "MTJNHU0JVB"
    searchKey = "5486225134d99f43826da401ee9bad57"

# Header config
[header]
  # FixIt 0.2.13 | CHANGED desktop header mode ("sticky", "normal", "auto")
  desktopMode = "sticky"
  # FixIt 0.2.13 | CHANGED mobile header mode ("sticky", "normal", "auto")
  mobileMode = "auto"
  # Header title config
  [header.title]
    # URL of the LOGO
    logo = "/logo.webp"
    # title name
    name = "菠菜众长"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    # whether to use typeit animation for title name
    typeit = false
  # FixIt 0.2.12 | NEW Header subtitle config
  [header.subtitle]
    # subtitle name
    name = "李瑞豪的博客"
    # whether to use typeit animation for subtitle name
    typeit = false

# FixIt 0.2.18 | NEW Breadcrumb config
[breadcrumb]
  enable = true
  sticky = true
  showHome = false

# Footer config
[footer]
  enable = true
  # FixIt 0.2.17 | CHANGED Custom content (HTML format is supported)
  # whether to show copyright info
  copyright = true
  # whether to show the author
  author = true
  # Site creation year
  since = 2018
  # FixIt 0.2.12 | NEW Public network security only in China (HTML format is supported)
  gov = ""
  # ICP info only in China (HTML format is supported)
  icp = ""
  # license info (HTML format is supported)
  license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a>'
  # FixIt 0.3.0 | NEW whether to show Hugo and theme info
  [footer.powered]
    enable = true
    hugoLogo = true
    themeLogo = true
  # FixIt 0.2.17 | CHANGED Site creation time
  [footer.siteTime]
    enable = true
    animate = true
    icon = "fa-solid fa-heartbeat"
    pre = "博客已运行"
    value = "2018-05-28T20:01:01+08:00"
  # FixIt 0.2.17 | NEW footer lines order, optional values: ["first", 0, 1, 2, 3, 4, 5, "last"]
  [footer.order]
    powered = 1
    copyright = 2
    statistics = 0
    visitor = "first"
    beian = 3

# Section (all posts) page config
[section]
  # special amount of posts in each section page
  paginate = 20
  # date format (month and day)
  dateFormat = "01-02"
  # amount of RSS pages
  rss = 20
  # FixIt 0.2.13 | NEW recently updated posts settings
  [section.recentlyUpdated]
    enable = true
    rss = true
    days = 30
    maxCount = 10

# List (category or tag) page config
[list]
  # special amount of posts in each list page
  paginate = 20
  # date format (month and day)
  dateFormat = "01-02"
  # amount of RSS pages
  rss = 20

# FixIt 0.2.17 | NEW TagCloud config for tags page
[tagcloud]
  enable = true
  min = 14 # Minimum font size in px
  max = 32 # Maximum font size in px
  peakCount = 10 # Maximum count of posts per tag
  orderby = "name" # Order of tags, optional values: ["name", "count"]

# Home page config
[home]
  # amount of RSS pages
  rss = 20
  # Home page profile
  [home.profile]
    enable = true
    # Gravatar Email for preferred avatar in home page
    gravatarEmail = ""
    # URL of avatar shown in home page
    avatarURL = "/images/avatar.jpg"
    # FixIt 0.2.17 | NEW identifier of avatar menu link
    avatarMenu = "about"
    # title shown in home page (HTML format is supported)
    title = "Lruihao's Note"
    # subtitle shown in home page
    subtitle = "不怕萬人阻擋，只怕自己投降"
    # whether to use typeit animation for subtitle
    typeit = true
    # whether to show social links
    social = true
    # disclaimer (HTML format is supported)
    disclaimer = ""
  # Home page posts
  [home.posts]
    enable = true
    # special amount of posts in each home posts page
    paginate = 10

# Social config about the author
[social]
  GitHub = "Lruihao"
  Weibo = "liahao"
  Email = "1024@lruihao.cn"
  RSS = true
  Stackoverflow = ""
  Zhihu = ""
  Douban = ""
  Gitea = ""
  Bilibili = ""
  BuyMeaCoffee = ""
  Linktree = ""
  QQ = ""
  QQGroup = ""
  CSDN = ""

# Page config
[page]
  # FixIt 0.2.18 | NEW whether to enable the author's avatar of the post
  authorAvatar = true
  # whether to hide a page from home page
  hiddenFromHomePage = false
  # whether to hide a page from search results
  hiddenFromSearch = false
  # FixIt 0.3.0 | NEW whether to hide a page from RSS feed
  hiddenFromRss = false
  # FixIt 0.3.0 | NEW whether to hide a page from related posts
  hiddenFromRelated = false
  # whether to enable twemoji
  twemoji = false
  # whether to enable lightgallery
  lightgallery = "force"
  # whether to enable the ruby extended syntax
  ruby = true
  # whether to enable the fraction extended syntax
  fraction = true
  # whether to enable the fontawesome extended syntax
  fontawesome = true
  # Default lisence of content.
  license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a>'
  # whether to show link to Raw Markdown content of the post
  linkToMarkdown = true
  # FixIt 0.3.0 | NEW whether to show link to view source code of the post
  linkToSource = true
  # FixIt 0.3.0 | NEW whether to show link to edit the post
  linkToEdit = true
  # FixIt 0.3.0 | NEW whether to show link to report issue for the post
  linkToReport = true
  # whether to show the full text content in RSS
  rssFullText = true
  # FixIt 0.2.13 | NEW Page style ("narrow", "normal", "wide", ...)
  pageStyle = "normal"
  # FixIt 0.2.17 | CHANGED Auto Bookmark Support
  # If true, save the reading progress when closing the page.
  autoBookmark = true
  # FixIt 0.2.17 | NEW whether to enable wordCount
  wordCount = true
  # FixIt 0.2.17 | NEW whether to enable readingTime
  readingTime = true
  # FixIt 0.2.17 | NEW end of post flag
  endFlag = "（本文完）"
  # FixIt 0.2.18 | NEW whether to enable instant.page
  instantPage = true
  # FixIt 0.3.0 | NEW whether to enable collection list at the sidebar
  collectionList = true
  # FixIt 0.3.0 | NEW whether to enable collection navigation at the end of the post
  collectionNavigation = true

  # Table of the contents config
  [page.toc]
    # whether to enable the table of the contents
    enable = true
    #  whether to keep the static table of the contents in front of the post
    keepStatic = false
    # whether to make the table of the contents in the sidebar automatically collapsed
    auto = true
    # FixIt 0.2.13 | NEW position of TOC ("left", "right")
    position = "right"
  # FixIt 0.2.13 | NEW Display a message at the beginning of an article to warn the reader that its content might be expired
  [page.expirationReminder]
    enable = true
    # Display the reminder if the last modified time is more than 90 days ago
    reminder = 90
    # Display warning if the last modified time is more than 180 days ago
    warning = 180
    # If the article expires, close the comment or not
    closeComment = true
  # FixIt 0.3.0 | NEW page heading config
  [page.heading]
    # used with `markup.tableOfContents.ordered` parameter
    [page.heading.number]
      # whether to enable auto heading numbering
      enable = true
      # FixIt 0.3.3 | NEW only enable in main section pages (default is posts)
      onlyMainSection = true
      [page.heading.number.format]
        h1 = "{title}"
        h2 = "{h2} {title}"
        h3 = "{h2}.{h3} {title}"
        h4 = "{h2}.{h3}.{h4} {title}"
        h5 = "{h2}.{h3}.{h4}.{h5} {title}"
        h6 = "{h2}.{h3}.{h4}.{h5}.{h6} {title}"
  # FixIt 0.2.16 | CHANGED KaTeX mathematical formulas
  [page.math]
    enable = false
    # default inline delimiter is $ ... $ and \( ... \)
    inlineLeftDelimiter = ""
    inlineRightDelimiter = ""
    # default block delimiter is $$ ... $$, \[ ... \], \begin{equation} ... \end{equation} and some other functions
    blockLeftDelimiter = ""
    blockRightDelimiter = ""
    # KaTeX extension copy_tex
    copyTex = true
    # KaTeX extension mhchem
    mhchem = true
  # Code config
  [page.code]
    # whether to show the copy button of the code block
    copy = true
    # FixIt 0.2.13 | NEW whether to show the edit button of the code block
    edit = true
    # the maximum number of lines of displayed code by default
    maxShownLines = 50
  # Mapbox GL JS config
  [page.mapbox]
    # access token of Mapbox GL JS
    accessToken = ""
    # style for the light theme
    lightStyle = "mapbox://styles/mapbox/light-v9"
    # style for the dark theme
    darkStyle = "mapbox://styles/mapbox/dark-v9"
    # whether to add NavigationControl
    navigation = true
    # whether to add GeolocateControl
    geolocate = true
    # whether to add ScaleControl
    scale = true
    # whether to add FullscreenControl
    fullscreen = true
  # FixIt 0.3.0 | NEW [Experimental] cache remote images locally, see: https://github.com/hugo-fixit/FixIt/pull/362
  [page.cacheRemoteImages]
    enable = false
    # replace remote image url with local image url (place in public/images/remote/)
    replace = false
  # FixIt 0.3.0 | NEW Related content config
  [page.related]
    enable = true
    count = 5
  # FixIt 0.2.17 | NEW Donate (Sponsor) settings
  [page.reward]
    enable = true
    animation = true
    # position relative to post footer, optional value: ["before", "after"]
    position = "before"
    comment = "Buy me a coffee~"
    # FixIt 0.2.18 | NEW display mode of QR code images, optional values: ["static", "fixed"], default: `static`
    mode = "fixed"
    [page.reward.ways]
      wechatpay = "/images/wechatpay.jpg"
      alipay = "/images/alipay.jpg"
      # paypal = "/images/paypal.png"
      # bitcoin = "/images/bitcoin.png"
  # FixIt CHANGED | 0.2.0 social share links in post page
  [page.share]
    enable = true
    Twitter = true
    Facebook = true
    Linkedin = true
    Weibo = true
    Baidu = true
  # FixIt NEW | 0.2.7 Third-party library config
  [page.library]
    [page.library.css]
      # someCSS = "some.css"
      # located in "assets/"
      # Or
      # someCSS = "https://cdn.example.com/some.css"
    [page.library.js]
      # someJavascript = "some.js"
      # Or
      # someJavascript = "https://cdn.example.com/some.js"
      flyfish = "/js/flyfish.js"
  # Page SEO config
  [page.seo]
    # image URL
    images = []
    # Publisher info
    [page.seo.publisher]
      name = "Lruihao"
      logoUrl = "/images/avatar.jpg"

# TypeIt config
[typeit]
  # typing speed between each step (measured in milliseconds)
  speed = 100
  # blinking speed of the cursor (measured in milliseconds)
  cursorSpeed = 1000
  # character used for the cursor (HTML format is supported)
  cursorChar = "|"
  # cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
  duration = -1

# FixIt 0.2.15 | NEW Mermaid config
[mermaid]
  # For values, see https://mermaid.js.org/config/theming.html#available-themes
  themes = ['default', 'dark']

# FixIt 0.2.12 | NEW PanguJS config
[pangu]
  # For Chinese writing
  enable = true
  selector = "article" # FixIt 0.2.17 | NEW

# FixIt 0.2.12 | NEW Watermark config
# Detail config see https://github.com/Lruihao/watermark#readme
[watermark]
  enable = true
  # watermark's text (HTML format is supported)
  content = '<img style="height: 0.85rem;" src="/logo.webp" alt="logo" /> 李瑞豪'
  # watermark's transparency
  opacity = 0.0125
  # watermark's width. unit: px
  width = 150
  # watermark's height. unit: px
  height = 20
  # row spacing of watermarks. unit: px
  rowSpacing = 60
  # col spacing of watermarks. unit: px
  colSpacing = 30
  # watermark's tangent angle. unit: deg
  rotate = 15
  # watermark's fontSize. unit: rem
  fontSize = 1.1
  # FixIt 0.2.13 | NEW watermark's fontFamily
  fontFamily = 'MMT_LRH,沐目体'

# FixIt 0.2.12 | NEW Busuanzi count
[ibruce]
  enable = false
  # Enable in post meta
  enablePost = false

# Site verification code config for Google/Bing/Yandex/Pinterest/Baidu
[verification]
  google = ""
  bing = ""
  yandex = ""
  pinterest = ""
  baidu = ""

# FixIt 0.2.10 | NEW Site SEO config
[seo]
  # image URL
  image = "/images/apple-devices-preview.webp"
  # thumbnail URL
  thumbnailUrl = "/images/tn.webp"

# FixIt 0.2.10 | NEW Analytics config
[analytics]
  enable = false
  # Google Analytics
  [analytics.google]
    id = ""
    # whether to anonymize IP
    anonymizeIP = true
  # Fathom Analytics
  [analytics.fathom]
    id = ""
    # server url for your tracker if you're self hosting
    server = ""

# Cookie consent config
[cookieconsent]
  enable = true
  # text strings used for Cookie consent banner
  [cookieconsent.content]
    message = ""
    dismiss = ""
    link = ""

# Compatibility config
[compatibility]
  # whether to use Polyfill.io to be compatible with older browsers
  polyfill = false
  # whether to use object-fit-images to be compatible with older browsers
  objectFit = false

# FixIt 0.2.14 | NEW GitHub banner in the top-right or top-left corner
[githubCorner]
  enable = true
  permalink = "https://github.com/Lruihao/hugo-blog"
  title = "在 GitHub 上查看程式碼，訂閱請點 Watch"
  position = "right" # ["left", "right"]

# FixIt 0.2.14 | NEW Gravatar config
[gravatar]
  enable = true
  # Gravatar host, default: "www.gravatar.com"
  host = "cravatar.cn" # "cravatar.cn", "gravatar.loli.net"
  style = "mp" # "", mp, identicon, monsterid, wavatar, retro, blank, robohash

# FixIt 0.2.16 | NEW Back to top
[backToTop]
  enable = true
  # Scroll percent label in b2t button
  scrollpercent = true

# FixIt 0.2.16 | NEW Reading progress bar
[readingProgress]
  enable = true
  # Available values: ["left", "right"]
  start = "left"
  # Available values: ["top", "bottom"]
  position = "top"
  reversed = false
  light = "#8581dd"
  dark = "#fff"
  height = "2px"

# FixIt 0.2.17 | NEW Progress bar in the top during page loading.
# For more information: https://github.com/CodeByZach/pace
[pace]
  enable = true
  # All available colors:
  # ["black", "blue", "green", "orange", "pink", "purple", "red", "silver", "white", "yellow"]
  color = "blue"
  # All available themes:
  # ["barber-shop", "big-counter", "bounce", "center-atom", "center-circle", "center-radar", "center-simple",
  # "corner-indicator", "fill-left", "flash", "flat-top", "loading-bar", "mac-osx", "material", "minimal"]
  theme = "minimal"

# FixIt 0.2.15 | NEW Developer options
[dev]
  enable = false
  # Check for updates
  c4u = false
  # Please do not expose to public!
  githubToken = ""
  # Mobile Devtools confi
  [dev.mDevtools]
    enable = false
    # "vConsole", "eruda" supported
    type = "vConsole"
