# -------------------------------------------------------------------------------------
# Front Matter Configuration
# See: https://gohugo.io/getting-started/configuration/#configure-front-matter
# -------------------------------------------------------------------------------------

lastmod = ["lastmod", ":fileModTime", ":git", ":defalut"]
