# -------------------------------------------------------------------------------------
# Theme Core Configuration
# See: https://fixit.lruihao.cn/theme-documentation-basics/#site-configuration
# -------------------------------------------------------------------------------------

[post_chat]
enable = false
hot_words = false

[post_summary]
enable = false

# FixIt 0.2.15 | NEW Developer options
# Select the scope named `public_repo` to generate personal access token,
# Configure with environment variable `HUGO_PARAMS_GHTOKEN=xxx`, see https://gohugo.io/functions/os/getenv/#examples
[dev]
enable = false
# Check for updates
c4u = false

# -------------------------------------------------------------------------------------
# Theme Components Configuration
# -------------------------------------------------------------------------------------

# Content adapters config for component projects
# https://github.com/hugo-fixit/component-projects
[projects_adapters]
enable = false
