# -------------------------------------------------------------------------------------
# Theme Core Configuration
# See: https://fixit.lruihao.cn/theme-documentation-basics/#site-configuration
# -------------------------------------------------------------------------------------

# which hash function used for SRI, when empty, no SRI is used
# ("sha256", "sha384", "sha512", "md5")
# fingerprint = "sha256"

# Comment config
[comment]
enable = true

[comment.valine]
enable = false
app_id = "7HwTRT0Q0Tfrat6ugrT6P67c-gzGzoHsz"
app_key = "mhTY1kuUmviCtQwkwOASfsfD"
# placeholder = "ヾﾉ≧∀≦)o~ 有事請留言！\n評論功能以郵件作為通知方式！\n如有必要請填寫正確郵箱哦！"
placeholder = "ヾﾉ≧∀≦)o~ 有事请留言！\n评论功能以邮件作为通知方式！\n如有必要请填写正确邮箱哦！"
avatar = "wavatar"
meta = ['nick','mail','link']
required_fields = ['nick','mail','link']
page_size = 10
lang = "zh-CN"
visitor = true
record_ip = true
highlight = true
enable_qq = true
server_urls = ""
#  emoji data file name, default is "google.yml"
# ("apple.yml", "google.yml", "facebook.yml", "twitter.yml")
# located in "themes/FixIt/assets/lib/valine/emoji/" directory
# you can store your own data files in the same path under your project:
# "assets/lib/valine/emoji/"
emoji = ""
comment_count = true

# Giscus comments config (https://giscus.app/)
[comment.giscus]
enable = true
repo = "Lruihao/hugo-blog"
repo_id = "MDEwOlJlcG9zaXRvcnk0MDQzNDY3MDk="
category = "General"
category_id = "DIC_kwDOGBnXVc4CApHL"
mapping = "title"
strict = "0"
term = ""
reactions_enabled = "1"
emit_metadata = "0"
input_position = "top" # ["top", "bottom"]
light_theme = "light"
dark_theme = "dark_dimmed"
lazy_load = true

# FixIt 0.3.10 | NEW Busuanzi count
[busuanzi]
# whether to enable busuanzi count
enable = true
# busuanzi count core script source. Default is https://vercount.one/js
source = "https://vercount.one/js"
# whether to show the site views
site_views = true
# whether to show the page views
page_views = true

# CDN config for third-party library files
[cdn]
# CDN data file name, disabled by default ["jsdelivr.yml", "unpkg.yml", ...]
# located in "themes/FixIt/assets/data/cdn/" directory
# you can store your own data files in the same path under your project: "assets/data/cdn/"
data = "unpkg.yml"

# FixIt 0.2.10 | NEW Analytics config
[analytics]
enable = true

# My share URL: https://cloud.umami.is/share/FSPwm1IsrQFY7ZvP/lruihao.cn
[analytics.umami]
data_website_id = "4049c0b0-87c9-4573-8ae5-d84449e40e05"
src = "https://cloud.umami.is/script.js"
data_host_url = ""
data_domains = ""
